# frozen_string_literal: true

source 'https://rubygems.org'

gem 'amazing_print'
gem 'benchmark-ips'
gem 'chronic'
gem 'clipboard'
gem 'command_kit'
gem 'fcom'
gem 'guard'
gem 'guard-shell'
gem 'memo_wise'
gem 'rainbow'
gem 'redis'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rspec'
gem 'ruby-lsp'
gem 'runger_style'
gem 'simple_cov-formatter-terminal'
gem 'slop'
gem 'tapp'
gem 'yard'
