[settings]
activate_aggressive = true
idiomatic_version_file_enable_tools = ["node", "ruby"]

[settings.status]
missing_tools = "always"

[settings.ruby]
compile = true

[tools]
node = "22.14.0"
python = "3.13.2"
ruby = "4.0.6"
