#!/usr/bin/env bash

set -euo pipefail # exit on any error, don't allow undefined variables, pipes don't swallow errors

if git diff --cached --name-only | rg --quiet '^config/locales/(en|es).json$' ; then
  i18n-tasks normalize > /dev/null 2>&1

  if [ "$?" = 0 ] ; then
    blue "Your i18n keys have been normalized."

    # Stage config/locales/ again if a newline-removal or
    # key-alphabetization diff was just introduced.
    if ! git diff --exit-code --quiet config/locales/ ; then
      git add config/locales/
    fi

    exit 0
  else
    red "There was an error normalizing your i18n keys."
    exit 1
  fi
fi
