#!/usr/bin/env bash

# Run Gitleaks to protect against committed secrets.

set -euo pipefail # exit on any error, don't allow undefined variables, pipes don't swallow errors

if gitleaks git --log-opts="origin/$(main-branch)..." &> /dev/null ; then
  echo 'Gitleaks did not detect any committed secrets.'
else
  gitleaks git --log-opts="origin/$(main-branch)..." --verbose
fi
