#!/usr/bin/env bash

set -euo pipefail # exit on any error, don't allow undefined variables, pipes don't swallow errors

is_text_file() {
  local file="$1"

  if file "$file" | grep -q 'text' ; then
    return 0
  else
    return 1
  fi
}

text_files() {
  while read -r file ; do
    if is_text_file "$file" ; then
      echo "$file"
    fi
  done
}

git_diff_hash_before=$(git diff | sha1sum | choose 0)

readarray -t files_to_lint_newlines < <(changed-not-deleted-files | text_files)

if [ ${#files_to_lint_newlines[@]} -eq 0 ] ; then
  write-background-notification 'No files need to be linted for newlines.'
else
  for file in "${files_to_lint_newlines[@]}" ; do
    # Ensure at least one trailing newline.
    sed -i -e '$a'\\ "$file"
    # Collapse multiple trailing newlines into one.
    sed -i -e ':a;N;$!ba;s/\n\+$//' "$file"
  done

  git_diff_hash_after=$(git diff | sha1sum | choose 0)

  if [ "$git_diff_hash_before" == "$git_diff_hash_after" ] ; then
    write-background-notification 'Changed text files all end with exactly one newline.'
  else
    write-background-notification 'Some files did not end with exactly one newline. They were all corrected.'
    exit 1
  fi
fi
