#!/usr/bin/env bash

# Run Prettier.

set -euo pipefail # exit on any error, don't allow undefined variables, pipes don't swallow errors

# Every file must have a period somewhere (either a dotfile or file extension).
# Crystal files, Ruby files, etc aren't linted by Prettier.
readarray -t files_for_prettier < <(
  changed-not-deleted-files | \
    rg '\.' | \
    rg -v '\.('\
'conf|'\
'cr|'\
'haml|'\
'lock|'\
'node-version|'\
'prettierignore|'\
'rb|'\
'ruby-version|'\
'sh|'\
'toml|'\
'zsh(rc)?'\
')$' || \
    true
)

git_diff_hash_before=$(git diff | sha1sum | choose 0)

if [ ${#files_for_prettier[@]} -eq 0 ]; then
  write-background-notification 'No files need to be linted by Prettier.'
else
  set +e
  (
    set -x
    ./node_modules/.bin/prettier --write --log-level=error "${files_for_prettier[@]}"
  )
  set -e

  git_diff_hash_after=$(git diff | sha1sum | choose 0)

  if [ "$git_diff_hash_before" == "$git_diff_hash_after" ] ; then
    write-background-notification 'Changed files satisfy Prettier.'
  else
    write-background-notification 'There were Prettier violation(s). They were all corrected.'
    exit 1
  fi
fi
