#!/usr/bin/env bash

# Run Betterleaks to protect against committed secrets.

set -euo pipefail # exit on any error, don't allow undefined variables, pipes don't swallow errors

if betterleaks git --log-opts="origin/$(main-branch)..." &> /dev/null ; then
  echo 'Betterleaks did not detect any committed secrets.'
else
  betterleaks git --log-opts="origin/$(main-branch)..." --verbose
fi
