name: JavaScript Checks

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Install pnpm
        run: npm install -g pnpm@10

      - name: Set pnpm store directory
        run: echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: Set up pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install NPM packages
        run: pnpm install --frozen-lockfile --loglevel=warn

      - name: Check Prettier
        run: ./node_modules/.bin/prettier . --check
